language: go
go:
  - "1.19"

os:
  - linux

dist: xenial

env:
  global:
    - GO111MODULE=on

services:
  - mysql
  - redis

cache:
  directories:
    - $GOPATH/pkg/mod

# work flow of entire CI lifecycle
#
# before_install
# install
# before_script
# script
# after_success / after_failure
# before_deploy
# deploy
# after_deploy
# after_script

before_install:
  # prepare MySQL
  - echo "Prepare MySQL"
  - mysql -e "CREATE DATABASE hexagonal"
  - sudo mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('root') WHERE User='root'; UPDATE user SET plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
  # Check Go Env
  - echo "Check Go Env"
  - echo "GOPATH:" $GOPATH
  - echo "GOROOT:" $GOROOT

install:
  - echo "Go Mod Tidy"
  - go mod tidy -v

before_script:
  - echo ""

script:
  # post script will still execute if pre script failed, replace with `pre-script && post-script` if you need
  - echo "Go Test"
  - go test ./... -v

notifications:
  slack:
    rooms:
      - rchack:S2eFIIU2Nc8vpU8QOqzvvVlD#travis-ci
    on_pull_requests: true
    on_success: always
    on_failure: always
